return {
    "CursorLine",
    "CursorLineNr",
    "LineNr",
    "LineNrAbove",
    "LineNrBelow",
    "Normal",
    "SignColumn",
    "StatusLine",
    "StatusLineNC",
    "TabLine",
    "TabLineFill",
    "TabLineSel",
    "WinBar",
    "WinBarNC",
}
